### ISSUE TITLE
not able to download vpc module

### ISSUE THREAD

**Issue by Divyanshutomar27** [hashicorp/learn-terraform-modules-use#1]
Hi Team,
i was trying make configurations usinf vpc module and when i ran command - terraform init, i got this error1 image file attached.

Also command  - "git clone https://github.com/hashicorp/learn-terraform-modules-use.git" on amazon linux 2 is not working though terraform is installed on it.

please advise.
![image](https://user-images.githubusercontent.com/36529072/123876845-b233fb80-d959-11eb-9b07-2b6a0dea951d.png)

![image](https://user-images.githubusercontent.com/36529072/123877453-d217ef00-d95a-11eb-97fe-037844aca6ce.png)

**Comment by im2nguyen** [comment]
Hi @Divyanshutomar27 , I don't believe you have git installed on your local machine. Both screenshots' error message show missing git

**Comment by Divyanshutomar27** [comment]
> Hi @Divyanshutomar27 , I don't believe you have git installed on your local machine. Both screenshots' error message show missing git

Hi @im2nguyen , i have installed git and now it is working fine, i am new in terraform and learning it, thanks.

**Comment by im2nguyen** [comment]
Happy to hear it works! Good luck on your Terraform adventure!
